### ISSUE TITLE
Could you make the tdlib package in the official Debian repo?

### ISSUE THREAD

**Issue by stokito** [sarg/tdlib-debian#1]
For the [tdlib-purple](https://github.com/BenWiederhake/tdlib-purple) we need to have the td debianized and available from the official Debain repo.
Maybe you can somehow make this possible?
As far I see the other peopls who may be interested are:
* https://wiki.debian.org/Teams/pkg-xmpp
* Thorsten "mirabilos" Glaser who was a maintainer of the old purple-telegram plugin: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=958828

**Comment by sarg** [comment]
Hey @stokito, I've moved to [Guix](https://guix.gnu.org/) nowadays and I'm not a Debian maintainer anyway. Feel free to use this repo as a base for your fresh build. `tdlib` doesn't need patching and the list of dependencies is very short, so building it is pretty straightforward. However they've stopped doing proper releases or even using tags, so you'll have to find which commit to build from the history.
